//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT2_TRANVANMINH_tvm_2210900112.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_DON_HANG
    {
        public int ID { get; set; }
        public int ID_DH { get; set; }
        public int ID_SP { get; set; }
        public int So_luong { get; set; }
        public Nullable<double> Don_Gia { get; set; }
    }
}
